Update: README.md
eight04/webext-launch-web-auth-flow pull request #8
Opened 2022-09-27 20:46 UTC by lucasrmendonca

- Use '#' for headers instead of '===' and '---';
- Add highlighting to the npm installation script;
- Replace the CommonJS usage example with ESM Module usage example;
- Add background persistent property in the permissions section;
- Improve clarity on some messages;
- Change unordered list markers from '*' to '-';

2022-09-28 02:22 UTC, eight04 commented
> * Replace the CommonJS usage example with ESM Module usage example;

Instead of replacing cjs example, it would be better to keep both of them e.g.
``````md
```
... cjs example ...
```

With Node.js@14+, you can load esm natively. Just import the default member from the package:

```
... esm example ...
```
``````

> * Add background persistent property in the permissions section;

Did you see any issue with event page?

2022-09-28 02:32 UTC, lucasrmendonca commented
> Instead of replacing cjs example, it would be better to keep both of them e.g.
I agree, will change it to include both.

> Did you see any issue with event page?
I ran into this error: https://stackoverflow.com/questions/13326105/using-webrequest-api-with-event-page

2022-09-28 03:37 UTC, eight04 commented
> I ran into this error: https://stackoverflow.com/questions/13326105/using-webrequest-api-with-event-page

What a silly bug. Then I suggest adding a note under the permission section:

```md
> **Note**: `webRequest` is not available to event page. See https://stackoverflow.com/questions/13326105/using-webrequest-api-with-event-page
```

2022-09-28 13:44 UTC, lucasrmendonca commented
> What a silly bug. Then I suggest adding a note under the permission section:

I have included it in item 2. of the Permissions section:

```
To polyfill `launchWebAuthFlow`, this library uses following API/permissions:

...
2. `webRequest` - this library cannot be used with non-persistent background pages, otherwise you'll get an error. To avoid this, set your background page `persistent` key to `true`.
```


What do you think of just updating it to include the stack overflow URL instead of adding the note?

2022-09-29 16:27 UTC, eight04 requested changes
LGTM!

2022-09-29 16:27 UTC, eight04 commented on README.md
> +import launchWebAuthFlow from "webext-launch-web-auth-flow";
Duplicate of line 15?

2022-10-01 01:34 UTC, lucasrmendonca commented on README.md
> +import launchWebAuthFlow from "webext-launch-web-auth-flow";
Oops, fixed.

2022-10-02 02:26 UTC, closed without merging